### ISSUE TITLE
java -jar ysoserial.jar CommonsBeanutils1 "command" xml

### ISSUE THREAD

**Issue by linuxwhy** [frohoff/ysoserial#108]
They told me that an old version of ysoserial.jar supported this type of generating: java -jar ysoserial.jar CommonsBeanutils1 "command" xml. But I tried almost all versions, none of them supported it. Can anyone give me a clue?

**Comment by frohoff** [comment]
ysoserial doesn't have any support for serialization formats other than the native Java `Serializable`-based one, though #38 may eventually explore adding other formats.
