### ISSUE TITLE
New CommonsCollections payload

### ISSUE THREAD

**Issue by scristalli** [frohoff/ysoserial#109]
Hello, would you be interested in adding a new payload for CommonsCollections 4.0?
It reuses some parts from other CommonsCollections payloads, but has a new entry point in the JDK.

Thank you.
Best regards.

**Comment by frohoff** [comment]
Sure. This project is mostly about trying to help people understand how these things work so any novel techniques or gadget classes are useful.

**Comment by scristalli** [comment]
Thanks, I was unsure because CommonsCollections has already been patched.
Will open a PR ASAP.
