### ISSUE TITLE
Error: Unable to access jarfile ysoserial.jar

### ISSUE THREAD

**Issue by sushantdhopat** [frohoff/ysoserial#152]
here is no any jar file 

root@kali:~/ysoserial# ls
appveyor.yml  assembly.xml  DISCLAIMER.txt  Dockerfile  LICENSE.txt  pom.xml  README.md  src  ysoserial.png
root@kali:~/ysoserial# java -jar ysoserial.jar
Error: Unable to access jarfile ysoserial.jar
root@kali:~/ysoserial#

**Comment by depsiFi** [comment]
Did you follow the installation instruction, buddy?

**Comment by sushantdhopat19** [comment]
there is no present file ysoserial.jar in ysoserial tool i didnt git any file like this that why i got this error

**Comment by depsiFi** [comment]
As mentioned in the Installation section, you should install this using mvn tool

**Comment by depsiFi** [comment]
Use jdk8, if you encounter any problems. And close this thread if you solved the problem.

**Comment by frohoff** [comment]
Assuming problem was resolved and closing for now.

**Comment by gpauwen** [comment]
I have the same error message. I git cloned the file, but there is no ysoserial.jar file anywhere. I am obviously missing something basic. The installation instructions just say download the file...
