### ISSUE TITLE
i can't found ysoserial.jar

### ISSUE THREAD

**Issue by fares2010dd** [frohoff/ysoserial#160]
how i run it??

**Comment by ProgramFilesx86** [comment]
https://jitpack.io/com/github/frohoff/ysoserial/master-SNAPSHOT/ysoserial-master-SNAPSHOT.jar

**Comment by frohoff** [comment]
Download link seems to be working AFAICT so closing for now.

**Comment by viniciuspereiras** [comment]
> https://jitpack.io/com/github/frohoff/ysoserial/master-SNAPSHOT/ysoserial-master-SNAPSHOT.jar

```Reusing existing connection to jitpack.io:443.
HTTP request sent, awaiting response... 404 Not Found
2022-06-20 13:14:21 ERROR 404: Not Found.``` :/

**Comment by Marmelat** [comment]
Any update ? 

"Not found"

**Comment by viniciuspereiras** [comment]
Yes, the best way to access files (or even repositories) deleted by GitHub (happens a lot with infosec stuff) is using Wayback machine, try access that: https://web.archive.org/web/20220520101432/https://jitpack.io/com/github/frohoff/ysoserial/master-8eb5cbfbf6-1/ysoserial-master-8eb5cbfbf6-1.jar

**Comment by karan999singh** [comment]
> 

Thanks
