### ISSUE TITLE
dependency scope setting issues

### ISSUE THREAD

**Issue by DataProvided** [frohoff/ysoserial#178]
Hi,

We are developing a tool to check whether the dependencies' scopes in maven are set rightly and reasonably. 

Our tools have found some issues in your project about scope setting in maven' pom.xml file.

- in `pom.xml`, `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-depchain` scope should be `test`  instead of `compile`.

Please help us confirm whether the above reports are right and explain why it should set like these.

Thanks a lot.

**Comment by frohoff** [comment]
needed at runtime for running tests in-situ with shaded jar
