### ISSUE TITLE
CommonsBeanutilsCollectionsLogging1 dependent commons-collections version

### ISSUE THREAD

**Issue by rungobier** [frohoff/ysoserial#18]
After testing, the version  CommonsBeanutilsCollectionsLogging1 dependent commons-collections package is from 2.0 to 3.2.2.
Sorry, my English is relatively poor.

**Comment by frohoff** [comment]
I had been leaving this open to test when I got around to #9 and #10. Does it indeed work with both commons-collections 2.0 and 3.2.2?
