### ISSUE TITLE
A tool for fuzzing the right payload

### ISSUE THREAD

**Issue by nirzaaa** [frohoff/ysoserial#207]
Hi guys!

While working on a PortSwigger lab, I had the problem of finding which payload should work in my case.
For this scenario I created this tool that helps to do the job for us automatically:
https://github.com/nirzaaa/LookingSerial

Video explanation about the tool:
https://www.youtube.com/watch?v=NAK_a324dco&list=PLGj3IZkhXGzL7SQII47kmo9OO3wsFPaVv&index=3

Your are more than welcome to take a look and leave a comment with your feedback and such,

Have a good one,

nirza

**Comment by frohoff** [comment]
Very cool tool, thank you for sharing. In the future please use the discussions feature for questions, comments, or troubleshooting not related to a bug.

https://github.com/frohoff/ysoserial/discussions

**Comment by nirzaaa** [comment]
> Very cool tool, thank you for sharing. In the future please use the discussions feature for questions, comments, or troubleshooting not related to a bug.
> 
> https://github.com/frohoff/ysoserial/discussions

Thank you for the kind words :)
I can definitely post there and delete this issue, was a mistake on my side.
Since then I also added a section on how to modify the script for specific cases too.

Have a good one,

nirza

**Comment by nirzaaa** [comment]
> Very cool tool, thank you for sharing. In the future please use the discussions feature for questions, comments, or troubleshooting not related to a bug.
> 
> https://github.com/frohoff/ysoserial/discussions

Hi :)

I hope I used the right place now, let me know what you think :)

https://github.com/frohoff/ysoserial/discussions/224

It really helped me and hope it will help others too, taking this great tool to the next level 💪
