### ISSUE TITLE
I don't know how to input next.

### ISSUE THREAD

**Issue by hitwh0071** [frohoff/ysoserial#208]
I didn't find this in google，what should i do next.
![image](https://github.com/frohoff/ysoserial/assets/50914668/42f191ac-bbdb-45e1-a62c-64c13dc6ddbc)

**Comment by hitwh0071** [comment]
![image](https://github.com/frohoff/ysoserial/assets/50914668/46784bc9-3dc8-47b7-b045-c2efec6103c8)

**Comment by frohoff** [comment]
Please use the discussions feature for questions or troubleshooting not related to a bug.

https://github.com/frohoff/ysoserial/discussions
