### ISSUE TITLE
Hello, I have some confusion about the code implementation of URLDNS

### ISSUE THREAD

**Issue by CC11001100** [frohoff/ysoserial#213]
Thank you for such an excellent open source project, I have some confusion about the code implementation of URLDNS, 

A custom URLStreamHandler was used here to block DNS resolution:
https://github.com/frohoff/ysoserial/blob/2874a69f6127fd3b3f078461741910423a6b1376/src/main/java/ysoserial/payloads/URLDNS.java#L56
But it also affects the hash code of the URL, causing the hash code obtained by the URL to be inconsistent with the original hash code:
![image](https://github.com/frohoff/ysoserial/assets/12819457/f93c3ffc-88f4-4f63-b315-9610ba4603d1)
The hashcode of the URL obtained at this point appears to be true, but in reality it is not:
![image](https://github.com/frohoff/ysoserial/assets/12819457/65b91e95-d42e-4b08-b44d-653cfd2271ed)
The true hashcode should be:
![image](https://github.com/frohoff/ysoserial/assets/12819457/4f81a927-4674-446a-9561-3662c840688c)
Subsequently, the hashcode cache in the URL was reset through reflection:
https://github.com/frohoff/ysoserial/blob/2874a69f6127fd3b3f078461741910423a6b1376/src/main/java/ysoserial/payloads/URLDNS.java#L59
This reflection looks quite troublesome because it also involves compatibility issues with the JDK version and introduces a dedicated library:
```xml
        <dependency>
            <groupId>com.nqzero</groupId>
            <artifactId>permit-reflect</artifactId>
            <version>0.3</version>
        </dependency>
```
My question is, since the hashcode needs to be cleaned up, why not just rewrite the hashcode method of URLStreamHandler in SilentURLStreamHandler and directly return -1? This way, the implementation is simpler and there is no need to consider compatibility issues
![image](https://github.com/frohoff/ysoserial/assets/12819457/6d3700ac-bfa2-40f1-8a30-10031b49f793)
Anyway, the hashcode is different from the original one. As for whether the hashcode of the key in HashMap is -1 or 12345678, it doesn't seem to be that important anymore?

Thank you again for bringing such an excellent project, and I hope you have time to help me clarify.

**Comment by UzJu** [comment]
mark

**Comment by frohoff** [comment]
Please use the discussions feature for questions or troubleshooting not related to a bug.

https://github.com/frohoff/ysoserial/discussions
