### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by Trinity-SYT-SECURITY** [frohoff/ysoserial#221]
![image](https://github.com/frohoff/ysoserial/assets/96654161/346227c8-0a0c-4b4e-89bc-dfae327f07df)
The Java versions are all confirmed to be correct. How can I solve this problem?

![image](https://github.com/frohoff/ysoserial/assets/96654161/e52c0d97-1c27-4e6e-82bb-43287a30047e)
![image](https://github.com/frohoff/ysoserial/assets/96654161/574953e0-957d-483f-98de-3dae0b40bfca)

**Comment by frohoff** [comment]
Fixed in #222
