### ISSUE TITLE
question about transformerChain

### ISSUE THREAD

**Issue by mudongliang** [frohoff/ysoserial#32]
In CommonsCollections1, you first create an useless `ChainedTransformer` : `transformerChain`(I say it's useless because only just constantTransformer(1)), then use the method decorate of `LazyMap` to create `TransformedMap`. At last, you use "java reflection" to modify the attribute `iTransformers` to malicious `transformers`. 
Why do you just directly set `transformerChain` with `transformers`? Or is there any security check that forbids this behavior?

**Comment by frohoff** [comment]
Generally any reflection at the end of gadget-chain set up is done to "arm" the chain because constructing it while armed can result in premature "detonation" during set-up and cause it to be inert when serialized and deserialized by the target application.

**Comment by mudongliang** [comment]
But the effect of code in the server side is the same in my mind.

**Comment by frohoff** [comment]
Going to close this for now. Please ask any further questions in the gitter channel: https://gitter.im/frohoff/ysoserial
