### ISSUE TITLE
Multiple Commands

### ISSUE THREAD

**Issue by raithedavion** [frohoff/ysoserial#56]
Is there a reason why this works "ping -c 4 <myip>" works, but "ping -c 2 <myip>; ping -c 2 <myip>" doesn't work when generating payloads?  I can't seem to get anything that isn't a single command to work (no output redirection, not multiple commands, etc.

**Comment by frohoff** [comment]
The short answer is that `Runtime.exec()` doesn't get passed through the shell and therefore doesn't support shell features/syntax such as `;`, `&`, `|`, `>`, `<`. The long answer is that it's complicated and you'll probably want to read [this](http://codewhitesec.blogspot.com/2015/03/sh-or-getting-shell-environment-from.html) for more info.

**Comment by frohoff** [comment]
Closing for now.
